### ISSUE TITLE
Batch Add Requests

### ISSUE THREAD

**Issue by rashidabbas786** [sflagp/QBXML-Object-Models#2]
Hello, Your work is appreciated. I loved it. well detailed. 

May I know if there is a way to make batch requests by converting your objects into xml?

**Comment by sflagp** [comment]
Hello Rashid,

Thank you for reaching out. You're the first one to do so. :) 
I haven't been actively working on this project as it was a way for me to sharpen my C# skills. I didn't write any batch request capabilities into it because the projects I worked on didn't require it. However; it is something I think that can be added. Can you tell me what you want to batch? Is it with the desktop version or the online version?

I played around a little bit this morning and created a AddBatchRqModel class. Below is the test method I created showing how it would work and the resulting XML. Is this what you were thinking you wanted to do?
```C#
        [TestMethod]
        public void TestBatchRq()
        {
            var invoices = new List<InvoiceAddRq>()
            {
                new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 1" }, Other = "Invoice add request 1" },
                new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 2" }, Other = "Invoice add request 2" },
                new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 3" }, Other = "Invoice add request 3" },
                new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 4" }, Other = "Invoice add request 4" },
                new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 5" }, Other = "Invoice add request 5" }
            };
            var batchRq = new AddBatchRqModel<InvoiceAddRq>("InvoiceAdd");
            batchRq.SetRequest(invoices, "AddRq");
            Assert.IsTrue(batchRq.ToString().Contains("<InvoiceAdd>"));
            Assert.IsTrue(batchRq.ToString().Contains("</InvoiceAddRq>"));
            Assert.IsTrue(batchRq.ToString().Contains("</QBXMLMsgsRq>"));
        }
```

```XML
<?xml version="1.0" encoding="utf-8"?><?qbxml version="15.0"?>
<QBXML>
	<QBXMLMsgsRq onError="stopOnError">
		<InvoiceAddRq>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 1</FullName>
				</CustomerRef>
				<Other>Invoice add request 1</Other>
			</InvoiceAdd>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 2</FullName>
				</CustomerRef>
				<Other>Invoice add request 2</Other>
			</InvoiceAdd>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 3</FullName>
				</CustomerRef>
				<Other>Invoice add request 3</Other>
			</InvoiceAdd>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 4</FullName>
				</CustomerRef>
				<Other>Invoice add request 4</Other>
			</InvoiceAdd>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 5</FullName>
				</CustomerRef>
				<Other>Invoice add request 5</Other>
			</InvoiceAdd>
		</InvoiceAddRq>
	</QBXMLMsgsRq>
</QBXML>
```

Let me know.

Thanks

**Comment by rashidabbas786** [comment]
Thank you so much, Greg. I appreciate your work and your instant solution to my request feature <3. 

Yes, this is what I was looking for. I'm building an application that has an import feature.

I did some workaround for this. Let me share my code. 

`    public static class ListExtensions
    {
        public static string? ToQbxml<T>(this List<T> list)
        {
            if (list == null || list.Count == 0)
            {
                return null;
            }
            XDocument qbdoc = XDocument.Parse(list.First()!.ToString()!);
            XElement addReqBody = qbdoc.Descendants("QBXMLMsgsRq").FirstOrDefault()!;
            addReqBody.RemoveNodes();
            foreach (var item in list)
            {
                XElement requestNodes = XDocument.Parse(item!.ToString()!).Descendants(item.GetType().Name).First();
                addReqBody.Add(requestNodes);
            }
            return qbdoc.ToString();
        }
    }`
    
    I know this is not an optimal solution. Would like to use your version. Will you be publishing an update on this?

**Comment by rashidabbas786** [comment]
Thank you so much, Greg. I appreciate your work and your instant solution to my request feature <3.

Yes, this is what I was looking for. I'm building an application that has an import feature.

I did some workaround for this. Let me share my code.
```
public static class ListExtensions
    {
        public static string? ToQbxml<T>(this List<T> list)
        {
            if (list == null || list.Count == 0)
            {
                return null;
            }
            XDocument qbdoc = XDocument.Parse(list.First()!.ToString()!);
            XElement addReqBody = qbdoc.Descendants("QBXMLMsgsRq").FirstOrDefault()!;
            addReqBody.RemoveNodes();
            foreach (var item in list)
            {
                XElement requestNodes = XDocument.Parse(item!.ToString()!).Descendants(item.GetType().Name).First();
                addReqBody.Add(requestNodes);
            }
            return qbdoc.ToString();
        }
    }
```
I know this is not an optimal solution. Would like to use your version. When can you roll out these updates?

**Comment by rashidabbas786** [comment]
> Hello Rashid,
> 
> Thank you for reaching out. You're the first one to do so. :) I haven't been actively working on this project as it was a way for me to sharpen my C# skills. I didn't write any batch request capabilities into it because the projects I worked on didn't require it. However; it is something I think that can be added. Can you tell me what you want to batch? Is it with the desktop version or the online version?
> 
> I played around a little bit this morning and created a AddBatchRqModel class. Below is the test method I created showing how it would work and the resulting XML. Is this what you were thinking you wanted to do?
> 
> ```cs
>         [TestMethod]
>         public void TestBatchRq()
>         {
>             var invoices = new List<InvoiceAddRq>()
>             {
>                 new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 1" }, Other = "Invoice add request 1" },
>                 new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 2" }, Other = "Invoice add request 2" },
>                 new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 3" }, Other = "Invoice add request 3" },
>                 new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 4" }, Other = "Invoice add request 4" },
>                 new InvoiceAddRq() { Customer = new(){ FullName = "Customer number 5" }, Other = "Invoice add request 5" }
>             };
>             var batchRq = new AddBatchRqModel<InvoiceAddRq>("InvoiceAdd");
>             batchRq.SetRequest(invoices, "AddRq");
>             Assert.IsTrue(batchRq.ToString().Contains("<InvoiceAdd>"));
>             Assert.IsTrue(batchRq.ToString().Contains("</InvoiceAddRq>"));
>             Assert.IsTrue(batchRq.ToString().Contains("</QBXMLMsgsRq>"));
>         }
> ```
> 
> ```
> <?xml version="1.0" encoding="utf-8"?><?qbxml version="15.0"?>
> <QBXML>
> 	<QBXMLMsgsRq onError="stopOnError">
> 		<InvoiceAddRq>
> 			<InvoiceAdd>
> 				<CustomerRef>
> 					<FullName>Customer number 1</FullName>
> 				</CustomerRef>
> 				<Other>Invoice add request 1</Other>
> 			</InvoiceAdd>
> 			<InvoiceAdd>
> 				<CustomerRef>
> 					<FullName>Customer number 2</FullName>
> 				</CustomerRef>
> 				<Other>Invoice add request 2</Other>
> 			</InvoiceAdd>
> 			<InvoiceAdd>
> 				<CustomerRef>
> 					<FullName>Customer number 3</FullName>
> 				</CustomerRef>
> 				<Other>Invoice add request 3</Other>
> 			</InvoiceAdd>
> 			<InvoiceAdd>
> 				<CustomerRef>
> 					<FullName>Customer number 4</FullName>
> 				</CustomerRef>
> 				<Other>Invoice add request 4</Other>
> 			</InvoiceAdd>
> 			<InvoiceAdd>
> 				<CustomerRef>
> 					<FullName>Customer number 5</FullName>
> 				</CustomerRef>
> 				<Other>Invoice add request 5</Other>
> 			</InvoiceAdd>
> 		</InvoiceAddRq>
> 	</QBXMLMsgsRq>
> </QBXML>
> ```
> 
> Let me know.
> 
> Thanks

I think xml needs some wrapping update, InvoiceAddRq should wrap each block individually 

```
<?xml version="1.0" encoding="utf-8"?><?qbxml version="15.0"?>
<QBXML>
	<QBXMLMsgsRq onError="stopOnError">
		<InvoiceAddRq>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 1</FullName>
				</CustomerRef>
				<Other>Invoice add request 1</Other>
			</InvoiceAdd>
                </InvoiceAddRq>
                <InvoiceAddRq>
			<InvoiceAdd>
				<CustomerRef>
					<FullName>Customer number 5</FullName>
				</CustomerRef>
				<Other>Invoice add request 5</Other>
			</InvoiceAdd>
		</InvoiceAddRq>
	</QBXMLMsgsRq>
</QBXML>
```

**Comment by sflagp** [comment]
I like your workaround. It's a very clean and concise. You are correct with the wrapping xml elements. According to this article on Stackoverflow; https://stackoverflow.com/questions/74210370/what-is-the-correct-structure-for-adding-multiple-time-activities-in-qbxml-quic, the person figured out that Intuit uses wrapping elements on some models but not on others. Intuit is not consistent with that.

I went ahead and added the wrapping elements because I think the majority of the models will require that. If I can't figure out an easy way to implement the logic in code, we may use your workaround for those rare models that don't need the wrapping elements :). 

The changes I made did not break any of my unit tests but I need to work on it some more to verify that it's working how it should be. Plus, I need to make it work with Mod requests in addition to the Add requests. I will work on it this weekend. In the meantime, I am attaching a beta version for you to try. It's a zip file that has both a nupkg that you can install into your local nuget store if you have one and if not, you can directly reference the dll that's in the zip file.

Also,if you like and are brave enough, I can give you access to the repo after I work on it this weekend. 

Let me know if there are any errors or anything else you need to have changed. 

[QbModels.1.2.5-beta01.zip](https://github.com/sflagp/QBXML-Object-Models/files/13675606/QbModels.1.2.5-beta01.zip)

**Comment by sflagp** [comment]
I worked on it a little more. Had to update the base result viewer to read the XML result for all the invoices. I had it hard coded to only read the first result of the batch request. I am attaching the updated beta file that you can use instead of the previous file I uploaded. 

I am attaching a quick test method I wrote to verify the results from the batch request for invoices. I use it in Visual Studio to look at the result in Quick Watch to analyze how it looks from a C# perspective.

I also created ModRqBatchModel class for batching mod requests.  I have not had a chance to test to see if it is working or not. I will work on this some more this weekend.

Let me know if you have any questions or if you have any issues.

[QbModels.1.2.5-beta04.zip](https://github.com/sflagp/QBXML-Object-Models/files/13679568/QbModels.1.2.5-beta04.zip)
[BatchInvoiceTest.txt](https://github.com/sflagp/QBXML-Object-Models/files/13679569/BatchInvoiceTest.txt)

**Comment by rashidabbas786** [comment]
Hello Greg,
Thank you for the above solutions. I will import your dll files into my project. Hopefully, it will work as expected. I'll let you know the results. 
Also, I was looking for ModeRq and you have already done it, bro.

Just to let you know, I would be able to test this with sales orders only.

Also would like to know, if these models support custom fields. I haven't tried. Hopefully, it will  be there

Cheers.
Have a great Weekend.

**Comment by sflagp** [comment]
Happy Saturday,

I found an issue with the ModBatchRqModel and fixed it. If you are going to try batching Mod requests, please use the beta v6 version below. Beta v4 generates an error when you try to get the QBXML. 

Sales orders is one of the few requests I can't test for (along with ARReundCreditCard, Currency, Estimate, Lead and Workers Comp). My QB does not support those features. So you doing Sales Orders is good because you can verify that I implemented the class correctly. If you can verify that everything is working, I will go ahead and publish a non-beta version to NuGet.

[QbModels.1.2.5-beta06.zip](https://github.com/sflagp/QBXML-Object-Models/files/13693922/QbModels.1.2.5-beta06.zip)

Thanks

**Comment by rashidabbas786** [comment]
Hello Greg, I will update you on this once I'm done with testing.
Currently, I'm working on invoices, I need to finish a few things to get it live.
