### ISSUE TITLE
Property missing from SalesOrderRetDto

### ISSUE THREAD

**Issue by dblood2** [sflagp/QBXML-Object-Models#8]
The DataExtRet property does not exist for the SalesOrder itself.  This property does exist in the SalesOrderLineRetDto.  The latter is a 
`List<QbModels.DataExtRetDto>` which is also appropriate for the SalesOrder.

The company file I'm working with has custom fields tied to both the Sales Order, and the Sales Order Lines. 

Any chance we could get this property added?  I don't mind creating a pull request, but it seems like a fairly quick addition.  Just let me know if you'd prefer the pull request. 

Great library - thank you!
Danny

**Comment by sflagp** [comment]
Hello Danny,

The DataExtRet is not something I really tested. Try this beta version and let me know if you see the results you want in SalesOrder. If it works, I will publish a non-beta version. If it doesn't work, send me a sample of the Qbxml response so that I make sure that I have the serializer reading and writing correctly.

Don't be afraid to let me know about the DataExtRet in other models. I'm sure it's not working in a lot of other places too.

[QbModels.1.2.11-beta01.zip](https://github.com/sflagp/QBXML-Object-Models/files/14314630/QbModels.1.2.11-beta01.zip)

Thanks

**Comment by dblood2** [comment]
Hey Greg, 

Thanks for such a quick response.  I installed the beta version and I can see the property now, but it didn't parse that part of the response into the object - the DataExtRet List exists, but it's empty.  

I attached an example response for a SalesOrder that I knew had custom fields.  I just set a breakpoint and copy/pasted the response, but it is the raw XML.  
[Example Response.txt](https://github.com/sflagp/QBXML-Object-Models/files/14315139/Example.Response.txt)

Just for completeness, here's the request:
[Example Request.txt](https://github.com/sflagp/QBXML-Object-Models/files/14315168/Example.Request.txt)

Let me know if you need anything else, and thanks again. 
Danny

**Comment by sflagp** [comment]
I see the issue. The documentation called it DataExtRetList but the element being returned is DataExtRet. Try this version.

Thanks

[QbModels.1.2.11-beta02.zip](https://github.com/sflagp/QBXML-Object-Models/files/14315272/QbModels.1.2.11-beta02.zip)

**Comment by dblood2** [comment]
Yep, that took care of it.  You're the man - thanks again.  

Danny

**Comment by sflagp** [comment]
Great. I will publish it to Nuget. Should be there in an hour or less depending on how quickly it is scanned.
